# Example alertmanager.yml configuration when using https://github.com/swarmstack/errbot-docker-alertmanager
#
# See https://errbot.io for how to configure Errbot default backends such as slack or email, or other Errbot docker images
#
# See https://github.com/mayflower/errbot-alerrtmanagerr for how to send alerts to the bot from Prometheus Alertmanager
#
# Change recipient/example.com to a user (e.g. my_username/companydomain.com) to receive direct alerts the bot, or join your bot
# to a channel and change recipient to the Room ID to have the bot announce alerts to everyone in a channel.
route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            #username: <user>#
            #channel: <channel>#
            #api_url: <url>#
