global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "docker_swarm_nodes-rules.yml"
  - "docker_swarm_services-rules.yml"
  - "portworx-rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: [ 'alertmanager:9093', 'alertmanagerB:9093' ]

scrape_configs:

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'pushgateway'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.pushgateway'
      type: 'A'
      port: 9091

  - job_name: 'grafana'
    dns_sd_configs:
    - names:
      - 'tasks.grafana'
      type: 'A'
      port: 3000

  - job_name: 'caddy'
    dns_sd_configs:
    - names:
      - 'tasks.caddy'
      type: 'A'
      port: 9180
