---
- hosts: all
  gather_facts: true
  remote_user: root
  vars:
    NETDATA_VERSION: netdata 1.11.1_rolling
    NETDATA_BRANCH: v1.11.1

  roles:
  - ../roles/common

  tasks:

  - name: Install requisite packages on SWARMJOIN host
    yum: name=ansible,git,httpd-tools state=latest
    when: "inventory_hostname == SWARMJOIN"

### INSTALL/UPDATE NETDATA ON ALL HOSTS
  - name: Determine if NetData is currently installed and version
    shell: if [ -f /sbin/netdata ]; then /sbin/netdata -v; else echo "not-installed"; fi
    args:
      executable: /bin/bash
    register: netdata_installed
    changed_when: False

  - name: Install or update NetData
    shell: rm -rf /tmp/netdata-install; mkdir -p /tmp/netdata-install; (cd /tmp/netdata-install; git clone --single-branch --branch {{NETDATA_BRANCH}} https://github.com/netdata/netdata.git --depth=1 && cd netdata; ./netdata-installer.sh --dont-wait) && rm -rf /tmp/netdata-install
    args:
      warn: no
      executable: /bin/bash
    ignore_errors: true
    changed_when: False
    when: "netdata_installed.stdout != NETDATA_VERSION"

  - name: Ensure NetData is enabled and started
    systemd: name=netdata state=started enabled=yes masked=no

### DOWNLOAD SWARMSTACK FILES TO SWARMJOIN HOST, COPY SOME LOCAL FILES TO SWARMJOIN HOST
  - name: Use git to download latest swarmstack
    git:
      repo: "{{ SWARMSTACK_REPO }}"
      dest: "{{ SWARMSTACK_SRC_DIR }}"
    ignore_errors: true
    when: "inventory_hostname == SWARMJOIN"

  - name: Check if local copy of swarmstack exists
    stat: path={{ SWARMSTACK_LOCAL_DIR }}
    changed_when: false
    register: localswarmstack
    when: "inventory_hostname == SWARMJOIN"

  - name: Create a local copy of swarmstack for editing
    shell: "rsync -aq --exclude=.git --exclude=.gitignore {{SWARMSTACK_SRC_DIR}}/ {{SWARMSTACK_LOCAL_DIR}}/"
    when: "inventory_hostname == SWARMJOIN and not localswarmstack.stat.exists"

  - name: gather name of host running ansible playbooks currently
    command: hostname
    delegate_to: localhost
    register: hostname
  - set_fact:
      ANSIBLE_HOST: hostname.stdout

  - name: Check if local copy of ansible role exists
    stat: path={{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/{{ CLUSTER }}
    changed_when: false
    register: localrole
    when: "inventory_hostname == SWARMJOIN"

  - name: move roles/swarmstack to roles/CLUSTER if directory doesn't exist on SWARMJOIN host
    command: mv {{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/swarmstack {{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/{{ CLUSTER }}
    when: "CLUSTER != 'swarmstack' and inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN and not localrole.stat.exists"

  - name: copy cluster file to SWARMJOIN host if different
    copy: src=../clusters/{{ CLUSTER }} dest={{ SWARMSTACK_LOCAL_DIR }}/ansible/clusters/{{ CLUSTER }} owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"

  - name: copy common.rules to SWARMJOIN host if different
    copy: src=../roles/common/files/etc/swarmstack_fw/rules/common.rules dest={{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/common/files/etc/swarmstack_fw/rules/common.rules owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"

  - name: copy cluster.rules to SWARMSTACK_LOCAL_DIR on SWARMJOIN host
    copy: src=../roles/{{ CLUSTER }}/files/etc/swarmstack_fw/rules/cluster.rules dest={{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/{{ CLUSTER }}/files/etc/swarmstack_fw/rules/cluster.rules owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"

  - name: copy docker.rules to SWARMSTACK_LOCAL_DIR on SWARMJOIN host
    copy: src=../roles/{{ CLUSTER }}/files/etc/swarmstack_fw/rules/docker.rules dest={{ SWARMSTACK_LOCAL_DIR }}/ansible/roles/{{ CLUSTER }}/files/etc/swarmstack_fw/rules/docker.rules owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"

  - name: copy alertmanager.yml to SWARMSTACK_LOCAL_DIR on SWARMJOIN host
    copy: src=../../alertmanager/conf/alertmanager.yml dest={{ SWARMSTACK_LOCAL_DIR }}/alertmanager/conf/alertmanager.yml owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"

  - name: copy prometheus.yml to SWARMSTACK_LOCAL_DIR on SWARMJOIN host
    copy: src=../../prometheus/conf/prometheus.yml dest={{ SWARMSTACK_LOCAL_DIR }}/prometheus/conf/prometheus.yml owner=root group=root mode="u=rw,g=r,o=r"
    when: "inventory_hostname == SWARMJOIN and ANSIBLE_HOST != SWARMJOIN"


### CONFIGURE PASSWORDS IN LOCAL COMPOSE FILE
  - name: Generate admin password hash for portainer
    shell: "htpasswd -nbB admin '{{ADMIN_PASSWORD}}' | cut -d ':' -f 2 | sed 's/\\$/\\$\\$/g'"
    register: portaineradminpw
    when: "inventory_hostname == SWARMJOIN"

  - name: Update docker-compose.yml with portainer admin password hash
    lineinfile:
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      regexp: "command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify"
      line: "    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password {{ item }}"
      backrefs: yes
    with_items: "{{portaineradminpw.stdout}}"
    when: "inventory_hostname == SWARMJOIN"

  - name: Update docker-compose.yml with web.external-url for alertmanager
    lineinfile:
      insertbefore: 'cluster.peer=alertmanagerB:9094'
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      line: "      - '--web.external-url=https://{{ EXTERNAL_ENDPOINT }}:9093/'"
    when: "inventory_hostname == SWARMJOIN"

  - name: Update docker-compose.yml with web.external-url for alertmanagerB
    lineinfile:
      insertbefore: 'cluster.peer=alertmanager:9094'
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      line: "      - '--web.external-url=https://{{ EXTERNAL_ENDPOINT }}:9095/'"
    when: "inventory_hostname == SWARMJOIN"

  - name: Update docker-compose.yml with web.external-url for Prometheus
    lineinfile:
      insertafter: 'storage.tsdb.retention'
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      line: "      - '--web.external-url=https://{{ EXTERNAL_ENDPOINT }}:9090/'"
    when: "inventory_hostname == SWARMJOIN"


### PROXY SETTINGS
  - name: Update docker-compose.yml with proxy settings for Caddy
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Caddy PROXY"
      marker_end: "SWARMSTACK_END Caddy PROXY"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertafter: '      - CADDYPATH='
      block: |2
              - http_proxy={{item.http_proxy}}
              - https_proxy={{item.https_proxy}}
              - no_proxy={{item.no_proxy}},{% for host in groups['swarm'] %}{{ hostvars[host].inventory_hostname }}{{ '' if loop.last else ','}}{% endfor %}
    with_items:
      - { http_proxy: "{{PROXY_HTTP}}", https_proxy: "{{PROXY_HTTPS}}", no_proxy: "{{PROXY_NOPROXY}}" }
    when: "inventory_hostname == SWARMJOIN and PROXY_ENABLED=='true'"

  - name: Update docker-compose.yml with proxy settings for Grafana
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Grafana PROXY"
      marker_end: "SWARMSTACK_END Grafana PROXY"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertbefore: '      - GF_SECURITY_ADMIN_USER='
      block: |2
              - http_proxy={{item.http_proxy}}
              - https_proxy={{item.https_proxy}}
              - no_proxy={{item.no_proxy}},{% for host in groups['swarm'] %}{{ hostvars[host].inventory_hostname }}{{ '' if loop.last else ','}}{% endfor %}
    with_items:
      - { http_proxy: "{{PROXY_HTTP}}", https_proxy: "{{PROXY_HTTPS}}", no_proxy: "{{PROXY_NOPROXY}}" }
    when: "inventory_hostname == SWARMJOIN and PROXY_ENABLED=='true'"


### LDAP SETTINGS
  - name: Add LDAP settings to new caddy/Caddyfile.ldap
    replace:
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/Caddyfile.ldap"
      regexp: '^    ldap url=.*$'
      replace: "    ldap url={{ (LDAP_USE_SSL == 'true') | ternary('ldaps','ldap') }}://{{LDAP_HOST}}:{{LDAP_PORT}},insecure={{LDAP_INSECURE}},timeout=5s,username={{LDAP_BIND_DN}},password={{LDAP_BIND_PASSWORD}},base=\"{{LDAP_SEARCH_BASE_DNS}}\",filter=\"{{LDAP_SEARCH_FILTER}}\""
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"
    ignore_errors: true

  - name: Add LDAP settings to grafana/ldap.toml
    lineinfile:
      path: "{{SWARMSTACK_LOCAL_DIR}}/grafana/ldap.toml"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^host =', line: "host = \"{{LDAP_HOST}}\"" }
      - { regexp: '^port =', line: "port = {{LDAP_PORT}}" }
      - { regexp: '^use_ssl =', line: "use_ssl = {{LDAP_USE_SSL}}" }
      - { regexp: '^start_tls =', line: "start_tls = {{LDAP_START_TLS}}" }
      - { regexp: '^bind_dn =', line: "bind_dn = \"{{LDAP_BIND_DN}}\"" }
      - { regexp: '^bind_password =', line: "bind_password = \"\"\"{{LDAP_BIND_PASSWORD}}\"\"\"" }
      - { regexp: '^search_filter =', line: "search_filter = \"{{LDAP_SEARCH_FILTER}}\"" }
      - { regexp: '^search_base_dns =', line: "search_base_dns = [\"{{LDAP_SEARCH_BASE_DNS}}\"]" }
      - { regexp: '^username =', line: "username = \"{{LDAP_ATTRIBUTE_USERNAME}}\"" }
      - { regexp: '^group_dn =', line: "group_dn = \"{{LDAP_GROUP_DN}}\"" }
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"
    ignore_errors: true

  - name: Update docker-compose.yml with caddy settings
    lineinfile:
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      regexp: "^    file: ./caddy/Caddyfile$"
      line: "    file: ./caddy/Caddyfile.ldap"
      backrefs: yes
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"

  - name: Update docker-compose.yml with grafana LDAP settings 1 of 4
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Grafana LDAP 1 of 4"
      marker_end: "SWARMSTACK_END Grafana LDAP 1 of 4"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertbefore: '  grafana_provisioning_datasources:'
      block: |2
          grafana_configuration:
            file: ./grafana/grafana.ini
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"

  - name: Update docker-compose.yml with grafana LDAP settings 2 of 4
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Grafana LDAP 2 of 4"
      marker_end: "SWARMSTACK_END Grafana LDAP 2 of 4"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertbefore: '  grafana_provisioning_datasources:'
      block: |2
          grafana_ldap:
            file: ./grafana/ldap.toml
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"

  - name: Update docker-compose.yml with grafana LDAP settings 3 of 4
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Grafana LDAP 3 of 4"
      marker_end: "SWARMSTACK_END Grafana LDAP 3 of 4"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertbefore: '      - source: grafana_dashboards_nodes'
      block: |2
              - source: grafana_configuration
                target: /etc/grafana/grafana.ini
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"

  - name: Update docker-compose.yml with grafana LDAP settings 4 of 4
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Grafana LDAP 4 of 4"
      marker_end: "SWARMSTACK_END Grafana LDAP 4 of 4"
      path: "{{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml"
      insertbefore: '      - source: grafana_dashboards_nodes'
      block: |2
              - source: grafana_ldap
                target: /etc/grafana/ldap.toml
    when: "inventory_hostname == SWARMJOIN and LDAP_ENABLED == 'true'"


### ADD PROMETHEUS SCRAPE CONFIGS FOR HOSTS
  - name: Add NetData to local Prometheus scrapes
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN NetData {{item}}"
      marker_end: "SWARMSTACK_END NetData {{item}}"
      path: "{{SWARMSTACK_LOCAL_DIR}}/prometheus/conf/prometheus.yml"
      block: |2
          - job_name: 'netdata-{{item}}'
            metrics_path: '/api/v1/allmetrics'
            params:
              format: [prometheus_all_hosts]
            honor_labels: true
            static_configs:
              - targets: ['{{item}}:19999']
    with_items: "{{groups['all']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add docker to local Prometheus scrapes
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN docker {{item}}"
      marker_end: "SWARMSTACK_END docker {{item}}"
      path: "{{SWARMSTACK_LOCAL_DIR}}/prometheus/conf/prometheus.yml"
      block: |2
          - job_name: 'dockerd-{{item}}'
            metrics_path: '/metrics'
            honor_labels: true
            static_configs:
              - targets: ['{{item}}:9323']
    with_items: "{{groups['swarm']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add etcd to local Prometheus scrapes
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN etcd {{item}}"
      marker_end: "SWARMSTACK_END etcd {{item}}"
      path: "{{SWARMSTACK_LOCAL_DIR}}/prometheus/conf/prometheus.yml"
      block: |2
          - job_name: 'etcd-{{item}}'
            metrics_path: '/metrics'
            honor_labels: true
            static_configs:
              - targets: ['{{item}}:2379']
    with_items: "{{groups['etcd']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add Portworx to local Prometheus scrapes
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN Portworx {{item}}"
      marker_end: "SWARMSTACK_END Portworx {{item}}"
      path: "{{SWARMSTACK_LOCAL_DIR}}/prometheus/conf/prometheus.yml"
      block: |2
          - job_name: 'portworx-{{item}}'
            metrics_path: '/metrics'
            honor_labels: true
            static_configs:
              - targets: ['{{item}}:9001']
    with_items: "{{groups['portworx']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

### MODIFY CADDY CONFIGS
  - name: Add all hosts to caddy/index.html javascript 
    blockinfile:
      marker_begin: "//SWARMSTACK_BEGIN js {{item}}"
      marker_end: "//SWARMSTACK_END js {{item}}"
      marker: "{mark}"
      insertbefore: 'SWARMSTACK JS MARKER'
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/index.html"
      block: |
        document.getElementById('{{hostvars[item]['inventory_hostname']}}').href = window.location.protocol + '//' + window.location.hostname + ':19998/{{hostvars[item]['inventory_hostname']}}/';
    with_items: "{{groups['all']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add all hosts to caddy/index.html BODY 
    blockinfile:
      marker_begin: "<!-- SWARMSTACK_BEGIN html {{item}} -->"
      marker_end: "<!-- SWARMSTACK_END html {{item}} -->"
      marker: "{mark}"
      insertbefore: 'SWARMSTACK HTML MARKER'
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/index.html"
      block: |
        <div class="boxes">
          <div class="linkbox"><a target="_blank" href="" id="{{hostvars[item]['inventory_hostname']}}"><h3>NetData - {{hostvars[item]['inventory_hostname']}}</h3></a></div>
          <div class="box">Everything happening on your systems and applications</div>
        </div>
    with_items: "{{groups['all']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add NetData proxy for all hosts to Caddyfile
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN NetData {{item}}"
      marker_end: "SWARMSTACK_END NetData {{item}}"
      insertbefore: 'SWARMSTACK MARKER'
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/Caddyfile"
      block: |2
          proxy /{{hostvars[item]['inventory_hostname']}} http://{{item}}:19999/ {
            without /{{hostvars[item]['inventory_hostname']}}
            transparent
          }
    with_items: "{{groups['all']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add NetData proxy for all hosts to Caddyfile.ldap example
    blockinfile:
      marker_begin: "SWARMSTACK_BEGIN NetData {{item}}"
      marker_end: "SWARMSTACK_END NetData {{item}}"
      insertbefore: 'SWARMSTACK MARKER'
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/Caddyfile.ldap"
      block: |2
          proxy /{{hostvars[item]['inventory_hostname']}} http://{{item}}:19999/ {
            without /{{hostvars[item]['inventory_hostname']}}
            transparent
          }
    with_items: "{{groups['all']}}"
    when: "inventory_hostname == SWARMJOIN"
    ignore_errors: true

  - name: Add CADDY_KEY template to Caddyfile if defined
    replace:
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/Caddyfile"
      regexp: 'CADDY_CERT'
      replace: '  tls {$CADDY_CERT} {$CADDY_KEY}'
    ignore_errors: true
    when: "inventory_hostname == SWARMJOIN and CADDY_KEY != ''"

  - name: Add CADDY_KEY template to Caddyfile.ldap if defined
    replace:
      path: "{{SWARMSTACK_LOCAL_DIR}}/caddy/Caddyfile.ldap"
      regexp: '^.*CADDY_CERT.*$'
      replace: '  tls {$CADDY_CERT} {$CADDY_KEY}'
    ignore_errors: true
    when: "inventory_hostname == SWARMJOIN and CADDY_KEY != ''"


### BOUNCE SWARMSTACK IF ALREADY RUNNING
  - name: Check if swarmstack is running
    shell: docker service ls | grep swarmstack_caddy; if [ $? -eq 1 ]; then echo 'notrunning'; else echo 'isrunning'; fi
    ignore_errors: true
    changed_when: false
    register: swarmstackrunning
    when: "inventory_hostname == SWARMJOIN"
   
  - name: Bring down swarmstack
    shell: "docker stack rm swarmstack; sleep 10"
    ignore_errors: true
    when: "inventory_hostname == SWARMJOIN and swarmstackrunning.stdout.find('isrunning') != -1"
   
  - name: Bring up swarmstack
    shell: "ADMIN_PASSWORD={{ADMIN_PASSWORD}} CADDY_CERT={{CADDY_CERT}} CADDY_KEY={{CADDY_KEY}} CADDY_URL={{CADDY_URL}} PUSH_USER={{PUSH_USER}} PUSH_PASSWORD={{PUSH_PASSWORD}} docker stack deploy -c {{SWARMSTACK_LOCAL_DIR}}/docker-compose.yml swarmstack"
    ignore_errors: true
    when: "inventory_hostname == SWARMJOIN"

...
