# An ansible cluster file in YAML format
# You would use this to manage a different Docker swarm cluster
all:
  vars:
    CLUSTER: another-example-cluster
    REBOOT_DELAY: 30     # For physical machines, try REBOOT_DELAY=300, and REBOOT_TIMEOUT=600
    REBOOT_TIMEOUT: 120  # Physical hosts may take much longer to boot
  children:

    swarm:
      children:

        swarm-managers:
          children:
            # Use groups of 3 nodes per label when using Portworx PX-Developer version.
            # Docker recommends no more than 7 manager nodes in a cluster.
            # 5 or 3 managers are warranted for smaller clusters.

            swarm-managers-RED:
              hosts:
                other-swarm-host1.ex.com:
                other-swarm-host2.ex.com:
                other-swarm-host3.ex.com:
              vars:
                DOCKER_LABEL: RED

            swarm-managers-BLUE:
              hosts:
                #other-swarm-host4.ex.com:
                #other-swarm-host5.ex.com:
              vars:
                DOCKER_LABEL: BLUE
          vars:
            ROLE: manager

        swarm-workers:
          children:

            swarm-workers-BLUE:
              hosts:
                #other-swarm-host6.ex.com:
              vars:
                DOCKER_LABEL: BLUE

            swarm-workers-GREEN:
              hosts:
                #other-swarm-host7.ex.com:
                #other-swarm-host8.ex.com:
                #other-swarm-host9.ex.com:
              vars:
                DOCKER_LABEL: GREEN
          vars:
            ROLE: worker 
      vars:
        JOIN: other-swarm-host1.ex.com        

    etcd:
      hosts:
        # You can use an existing etcd cluster, Portworx storage metadata is keyed by CLUSTERID 
        swarm01.ex.com:
        swarm02.ex.com:
        swarm03.ex.com:

    portworx:
      children:

        portworx-RED:
          hosts:
            other-swarm-host1.ex.com:
              vars:
                #DEVICES: '["/dev/sdc"]'  # You can override the devices and interfaces per-host
            other-swarm-host2.ex.com:
            other-swarm-host3.ex.com:
          vars:
            CLUSTERID: portworx-RED

        portworx-BLUE:
          hosts:
            #other-swarm-host4.ex.com:
            #other-swarm-host5.ex.com:
            #other-swarm-host6.ex.com:
          vars:
            CLUSTERID: portworx-BLUE
      vars:
        DEVICES: '["/dev/sdb"]'
        DATAIFACE: eth0
        MGTIFACE: eth0
